[package]
name = "smpp"
version = "0.1.0"
authors = ["Iain H"]
edition = "2018"

[dependencies]
bytes = "0.6"
num_enum = "0.5"
tokio = { version = "0.3", features = ["full"] }

[dev-dependencies]
argh = "0.1"

[[example]]
name = "send_sms"