[package]
name = "smpp"
version = "0.1.0"
authors = ["Iain H"]
edition = "2021"

[dependencies]
bytes = "1.5"
num_enum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
argh = "0.1"
tracing-subscriber = "0.3"

[[example]]
name = "send_sms"
